source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FloatingActionButton_Example', :exclusive => true do
  pod "FloatingActionButton", :path => "../"
  pod "SnapKit"
end

target 'FloatingActionButton_Tests', :exclusive => true do
  pod "FloatingActionButton", :path => "../"

  
end
