source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FloatingActionButton_Example' do
  pod "FloatingActionButton", :path => "../"
  pod "SnapKit", "3.0.2"
end

target 'FloatingActionButton_Tests' do
  pod "FloatingActionButton", :path => "../"

  
end
